# Generated by Django 3.2.12 on 2022-03-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.TextField(),
        ),
    ]
