# Generated by Django 3.2.12 on 2022-03-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arike', '0002_alter_facility_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='facility',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='arike.facility'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='kind',
            field=models.CharField(choices=[('phc', 'PHC'), ('chc', 'CHC')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arike.district'),
        ),
    ]
