# Generated by Django 3.2.12 on 2022-03-06 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arike', '0007_auto_20220306_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familydetail',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='familydetail',
            name='remarks',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='visit_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arike.visitdetails'),
        ),
        migrations.AlterField(
            model_name='treatmentnotes',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arike.visitdetails'),
        ),
    ]
