# Generated by Django 3.2.12 on 2022-03-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arike', '0008_auto_20220306_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdisease',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arike.treatment'),
        ),
        migrations.AlterField(
            model_name='patientdisease',
            name='note',
            field=models.TextField(max_length=100),
        ),
    ]
